- name: Destroy network
  docker_network:
    name: '{{ docker_testenv_network_name }}'
    state: absent
    force: true

- name: Stop testing container
  docker_container:
    name: '{{ item.name }}'
    state: absent
  loop: '{{ docker_testenv_hosts }}'
