- hosts: localhost
  vars:
    docker_testenv_hosts:
      - name: foo.example.com
        image: docker.io/centos:8
        command: sleep inf
      - name: bar.example.com
        image: docker.io/centos:8
        command: sleep inf
  roles:
    - setup

- import_playbook: '{{ playbook_dir }}/playbook.yml'

- hosts: localhost
  roles:
    - teardown
