- name: Check if all hosts from inventory has matching container
  fail:
    msg: 'Hosts {{ _undefined_hosts | join(", ") }} doesn''t have defined containers.'
  when: _undefined_hosts | length > 0
  vars:
    _inventory_hosts: '{{ query("inventory_hostnames", "all:!localhost") }}'
    _container_hosts: '{{ docker_testenv_hosts | map(attribute="name") | list }}'
    _undefined_hosts: '{{ _inventory_hosts | difference(_container_hosts) }}'

# Need them in all plays that are executed on host. Teardown sub-role then can
# be executed without duplicating vars to another play.
- name: Add role params to facts
  set_fact:
    '{{ item }}': '{{ lookup("vars", item) }}'
  loop: '{{ vars.keys() | select("match", "^docker_testenv_") | list }}'

- name: Build testing images
  docker_image:
    name: '{{ item.image }}'
    source: build
    build:
      path: '{{ item.build }}'
      pull: true
    force_source: true
    state: present
  when: item.build | default('') | length > 0
  loop: '{{ docker_testenv_hosts }}'

- name: Start testing containers
  docker_container:
    name: '{{ item.name }}'
    hostname: '{{ item.name }}'
    image: '{{ item.image }}'
    working_dir: '{{ item.workdir | default(omit) }}'
    entrypoint: '{{ item.entrypoint | default(omit) }}'
    command: '{{ item.command | default(omit) }}'
    volumes: '{{ item.volumes | default(omit) }}'
    state: started
    recreate: true
  loop: '{{ docker_testenv_hosts }}'

- name: Create network
  docker_network:
    name: '{{ docker_testenv_network_name }}'
    connected: '{{ docker_testenv_hosts | map(attribute="name") | list }}'
    state: present
  when: docker_testenv_hosts | length > 1

- name: Add contaner to inventory
  add_host:
    name: '{{ item.name }}'
    ansible_connection: docker
    ansible_become_method: su
  loop: '{{ docker_testenv_hosts }}'

- name: Check if containers are running
  command: 'true'
  changed_when: false
  delegate_to: '{{ item.name }}'
  loop: '{{ docker_testenv_hosts }}'
