- name: Destroy network
  docker_network:
    name: '{{ ansible_testing_network_name }}'
    state: absent
    force: true

- name: Stop testing container
  docker_container:
    name: '{{ item.name }}'
    state: absent
  loop: '{{ ansible_testing_hosts }}'
