- hosts: foo
  tasks:
    - name: Print host variable
      debug:
        msg: '{{ message }}'

    - name: Create new example file
      copy:
        dest: /tmp/new-file
        content: New File Content
