- hosts: foo
  tasks:
    - name: Print host variable
      debug:
        msg: '{{ message }}'

    - name: Get hostname
      command: hostname
      register: hostname_cmd

    - name: Print hostname
      debug:
        var: hostname_cmd.stdout

    - name: Create new example file
      copy:
        dest: /tmp/new-file
        content: New File Content
