# setup environment - build and start docker containers
- hosts: localhost
  vars:
    ansible_testing_hosts:
      - name: foo.example.com
        image: docker.io/centos:8
        command: sleep inf
  roles:
    - setup


# launch playbook
- import_playbook: '{{ playbook_dir }}/playbook.yml'


# tests
- hosts: foo
  tasks:
    - command: test -f /tmp/new-file

    - block:
        - command: test -f /tmp/does-not-exist
        - fail:
            msg: FAIL, command should fail
      rescue:
        - debug:
            msg: OK, expected to fail


# terdown - stop and remove docker containers
- hosts: localhost
  roles:
    - teardown
