# Need them in all plays that are executed on host
- name: Add role params to facts
  set_fact:
    '{{ item }}': '{{ vars[item] }}'
  loop: '{{ vars.keys() | select("match", "^ansible_testing_") | list }}'

- name: Build testing images
  docker_image:
    name: '{{ item.image }}'
    source: build
    build:
      path: '{{ item.build }}'
      pull: true
    force_source: true
    state: present
  when: item.build | default('') | length > 0
  loop: '{{ ansible_testing_hosts }}'

- name: Start testing containers
  docker_container:
    name: '{{ item.name }}'
    image: '{{ item.image }}'
    working_dir: '{{ item.workdir | default(omit) }}'
    entrypoint: '{{ item.entrypoint | default(omit) }}'
    command: '{{ item.command | default(omit) }}'
    volumes: '{{ item.volumes | default(omit) }}'
    state: started
    recreate: true
  loop: '{{ ansible_testing_hosts }}'

- name: Create network
  docker_network:
    name: '{{ ansible_testing_network_name }}'
    connected: '{{ ansible_testing_hosts | map(attribute="name") | list }}'
    state: present
  when: ansible_testing_hosts | length > 1

- name: Add contaner to inventory
  add_host:
    name: '{{ item.name }}'
    ansible_connection: docker
    ansible_become_method: su
  loop: '{{ ansible_testing_hosts }}'

- name: Check if containers are running
  command: 'true'
  delegate_to: '{{ item.name }}'
  loop: '{{ ansible_testing_hosts }}'
